/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infoq.view;

import br.com.infoq.dao.UsuarioDAO;
import br.com.infoq.fabrica.Conexao;
import br.com.infoq.model.Usuario;
import br.com.infoq.model.Usuario.Perfil;
import static br.com.infoq.view.TelaPrincipal.desktop;
import java.awt.Color;
import java.util.Optional;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Grazi
 */
public class frmLogin extends javax.swing.JFrame {
    UsuarioDAO dao = new UsuarioDAO();
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        ImageIcon icone = new ImageIcon(getClass().getResource("icons/user.png"));
        setIconImage(icone.getImage());

        boolean conexao = Conexao.testarConexao();
        String imagem = "dbok.png";
        if (!conexao)
            imagem = "dberro.png";
        lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("icons/"+imagem)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        lblstatus = new javax.swing.JLabel();
        lb_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyReleased(evt);
            }
        });
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(185, 113, 330, 40);

        txt_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_senha);
        txt_senha.setBounds(185, 180, 330, 40);

        btn_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cadeado icone 40x40.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(303, 233, 210, 50);

        lblstatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(248, 248, 248));
        lblstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dberro.png"))); // NOI18N
        getContentPane().add(lblstatus);
        lblstatus.setBounds(10, 20, 50, 40);

        lb_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login.jpg"))); // NOI18N
        lb_fundo.setMinimumSize(new java.awt.Dimension(450, 230));
        lb_fundo.setPreferredSize(new java.awt.Dimension(450, 230));
        getContentPane().add(lb_fundo);
        lb_fundo.setBounds(0, 0, 530, 310);

        setSize(new java.awt.Dimension(535, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        logar();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaActionPerformed
        logar();
    }//GEN-LAST:event_txt_senhaActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioKeyReleased

    private void txt_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyPressed

        // COMANDO PARA PLUAR PARA PROXIMO CAMPO
        if (evt.getKeyCode() == evt.VK_ENTER) {

            txt_senha.requestFocus();
            // campo2.requestFocus();
            // botao.requestFocus();

        }


    }//GEN-LAST:event_txt_usuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel lb_fundo;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
    
    public void logar() {
        Optional<Usuario> opt = dao.validarLogin(txt_usuario.getText().trim(), String.valueOf(txt_senha.getPassword()));
        if(opt.isPresent()){
            Usuario usuario = opt.get();
            Optional<Perfil> optPerfil = Optional.ofNullable(usuario.getPerfil());

            TelaPrincipal principal = new TelaPrincipal();
            principal.setVisible(true);
            principal.lblUsuario.setText(usuario.getUsuario());
                
            TelaMenu menu = new TelaMenu();
            desktop.add(menu);
            menu.setVisible(true);
                
            if(optPerfil.isPresent() && optPerfil.get().equals(Perfil.ADMIN)){
                principal.menuCadUsu.setEnabled(true);
                menu.btn_usuarios.setEnabled(true);
                principal.lblUsuario.setForeground(Color.blue);
            }
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuário ou Senha inválido");
        }
   }


}
