package br.com.infoq.view;

import java.util.List;
import java.util.Optional;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import br.com.infoq.exception.IdIncorretoException;
import br.com.infoq.exception.UsuarioNotFoundException;
import br.com.infoq.model.Usuario;
import br.com.infoq.service.SwingOptions;
import br.com.infoq.service.UsuarioService;
import br.com.infoq.utils.SwingUtils;
/**
 *
 * @author tiagods
 *
 */

@Component
public class TelaUsuario extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    
    @Autowired private UsuarioService usuarios;
    @Autowired private SwingOptions swing;
    
    public TelaUsuario() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    private Usuario usuarioBuilder(Optional<Long> result) {
        Usuario usuario = new Usuario(
                result.isPresent() ? result.get() : -1L,
                txtNome.getText(),
                txtTel.getText(),
                txtLogin.getText(),
                new String(txtSenha.getPassword()),
                cbPerfil.getSelectedItem().toString()
        );
        return usuario;
    }

    private boolean validar() {
        if ((txtNome.getText().isEmpty()) || (new String(txtSenha.getPassword()).isEmpty()) || (txtLogin.getText().isEmpty()) || (cbPerfil.getSelectedItem().equals(""))) {
            JOptionPane.showMessageDialog(null, "Preencha os Dados!!");
            return false;
        }
        return true;
    }

    private Optional<Long> validarId() throws IdIncorretoException {
        if(txtId.getText().trim().isEmpty()) return Optional.empty();
        try {
            Long id = Long.parseLong(txtId.getText().trim());
            return Optional.of(id);
        } catch (Exception e) {
            throw new IdIncorretoException("Campo id incorreto");
        }
    }

    private void limparCampos() {
        SwingUtils.limparCampos(getContentPane());
        txtLogin.setEditable(true);
        cbPerfil.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setBounds(190, 239, 14, 17);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(190, 280, 36, 17);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(190, 321, 33, 17);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(538, 321, 38, 17);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(538, 362, 28, 17);
        txtId = new javax.swing.JTextField();
        txtId.setBounds(251, 236, 78, 23);
        txtNome = new javax.swing.JTextField();
        txtNome.setBounds(251, 277, 490, 23);
        txtLogin = new javax.swing.JTextField();
        txtLogin.setBounds(251, 318, 152, 23);
        txtSenha = new javax.swing.JPasswordField();
        txtSenha.setBounds(586, 318, 152, 23);
        cbPerfil = new javax.swing.JComboBox<String>();
        cbPerfil.setBounds(586, 359, 152, 23);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(190, 362, 40, 17);
        btnNovo = new javax.swing.JButton();
        btnNovo.setBounds(211, 425, 129, 73);
        btnDeletar = new javax.swing.JButton();
        btnDeletar.setBounds(580, 425, 143, 73);
        btnSalvar = new javax.swing.JButton();
        btnSalvar.setBounds(400, 425, 139, 73);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setBounds(749, 85, 128, 109);
        txtTel = new javax.swing.JFormattedTextField();
        txtTel.setBounds(251, 359, 152, 23);
        jButton1 = new javax.swing.JButton();
        jButton1.setBounds(874, 11, 40, 40);
        jPanel3 = new javax.swing.JPanel();
        jPanel3.setBounds(190, 11, 551, 207);
        txPesquisar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbUsuarios = new javax.swing.JTable();

        setClosable(true);
        setTitle("Usuários");
        setPreferredSize(new java.awt.Dimension(948, 688));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome");
        jLabel2.setMaximumSize(new java.awt.Dimension(0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Login");
        jLabel3.setMaximumSize(new java.awt.Dimension(0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Senha");
        jLabel4.setMaximumSize(new java.awt.Dimension(0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Perfil");
        jLabel5.setMaximumSize(new java.awt.Dimension(0, 0));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtId.setMaximumSize(new java.awt.Dimension(0, 0));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.setMaximumSize(new java.awt.Dimension(0, 0));

        txtLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLogin.setMaximumSize(new java.awt.Dimension(0, 0));

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSenha.setMaximumSize(new java.awt.Dimension(0, 0));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        cbPerfil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPerfil.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "user", "admin" }));
        cbPerfil.setToolTipText("");
        cbPerfil.setMaximumSize(new java.awt.Dimension(0, 0));
        cbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPerfilActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Celular");
        jLabel6.setMaximumSize(new java.awt.Dimension(0, 0));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inserir.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.setToolTipText("Adicionar");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/deletar.png"))); // NOI18N
        btnDeletar.setText("EXCLUIR");
        btnDeletar.setToolTipText("Remover");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salvar.png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setToolTipText("Editar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users.png"))); // NOI18N

        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTel.setMaximumSize(new java.awt.Dimension(0, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_sair_25_25.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Usuario"));
        jPanel3.setToolTipText("");
        jPanel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 176));

        txPesquisar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txPesquisar.setToolTipText("");
        txPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPesquisarActionPerformed(evt);
            }
        });
        txPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txPesquisarKeyReleased(evt);
            }
        });

        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "LOGIN", "NOME", "PERFIL"
            }
        ) {
            /**
			 * 
			 */
			private static final long serialVersionUID = 3794838593713119354L;
			boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);
        jScrollPane3.setViewportView(tbUsuarios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(txPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        getContentPane().add(jPanel3);
        getContentPane().add(jLabel1);
        getContentPane().add(jLabel2);
        getContentPane().add(jLabel3);
        getContentPane().add(jLabel6);
        getContentPane().add(txtTel);
        getContentPane().add(txtLogin);
        getContentPane().add(jLabel4);
        getContentPane().add(jLabel5);
        getContentPane().add(txtSenha);
        getContentPane().add(cbPerfil);
        getContentPane().add(txtId);
        getContentPane().add(txtNome);
        getContentPane().add(btnNovo);
        getContentPane().add(btnSalvar);
        getContentPane().add(btnDeletar);
        getContentPane().add(jButton1);
        getContentPane().add(jLabel7);

        setBounds(0, 0, 940, 685);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        remover();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void cbPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPerfilActionPerformed

    private void txtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyPressed

    }//GEN-LAST:event_txtIdKeyPressed

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased

    }//GEN-LAST:event_txtIdKeyReleased

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed

    }//GEN-LAST:event_txtIdActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        swing.abrirTelaMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPesquisarActionPerformed

    private void txPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesquisarKeyReleased
        pesquisar();
    }//GEN-LAST:event_txPesquisarKeyReleased

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        preencherForm();
    }//GEN-LAST:event_tbUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbPerfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbUsuarios;
    private javax.swing.JTextField txPesquisar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTel;
    // End of variables declaration//GEN-END:variables

    public void pesquisar() {
        SwingUtils.limparTabela(tbUsuarios);
        List<Usuario> lista = txPesquisar.getText().trim().equals("") ? usuarios.listar() : usuarios.buscarPorNome(txPesquisar.getText());
        DefaultTableModel dm = (DefaultTableModel)tbUsuarios.getModel();
        lista.forEach(c->dm.addRow(new Object[]{c.getId(), c.getLogin(), c.getUsuario(), c.getPerfil()}));
    }
    
    private void preencherForm() {
        int setar = tbUsuarios.getSelectedRow();
        if(setar==-1) return;
        txtId.setText(tbUsuarios.getModel().getValueAt(setar, 0).toString());
        Optional<Long> result = Optional.empty();
        try {
            result = validarId();
            if (!result.isPresent()) { return; }
        } catch (IdIncorretoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        try {
            Optional<Usuario> opt = usuarios.buscarPorId(result.get());
            Usuario us = opt.get();
            preencherForm(us);
        } catch (UsuarioNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Usuário não Cadastrado");
            limparCampos();
        }
    }

    private void preencherForm(Usuario us) {
        txtId.setText(us.getId() + "");
        txtNome.setText(us.getUsuario());
        txtTel.setText(us.getFone());
        txtLogin.setText(us.getLogin());
        txtSenha.setText(us.getSenha());
        cbPerfil.setSelectedItem(us.getPerfil());
        txtLogin.setEditable(false);
    }

    private void salvar() {
        if (!validar()) {
            return;
        }
        Optional<Long> result = Optional.empty();
        try {
            result = validarId();
        } catch (IdIncorretoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return;
        }
        Optional<Usuario> buscarLogin = usuarios.buscarLogin(txtLogin.getText());
        if (buscarLogin.isPresent() && 
                (result.isPresent() ? buscarLogin.get().getId() != result.get() : true)
                ) {
            JOptionPane.showMessageDialog(null, "Login ja existe, tente informar outro!");
            return;
        }
        try{
            if(result.isPresent()) 
               usuarios.alterar(usuarioBuilder(result), result.get());
            else
               usuarios.adicionar(usuarioBuilder(Optional.empty()));
            JOptionPane.showMessageDialog(null, "Registro salvo com Sucesso!");
            limparCampos();
            pesquisar();
        } catch(UsuarioNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void remover() {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                Optional<Long> result = validarId();
                if (!result.isPresent()) { return; }
                usuarios.deletar(result.get());
                JOptionPane.showMessageDialog(null, "Registro Apagado com Sucesso!");
                limparCampos();
            } catch (UsuarioNotFoundException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } catch (IdIncorretoException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            pesquisar();
        }
    }

}
