spring:
 jpa:
  hibernate:ddl-auto: none
 datasource:
  url: jdbc:h2:./data/db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  username: root
  password: Info@1234
 flyway:
  baselineOnMigrate:true
  validate-on-migrate:false